### ISSUE TITLE
links broken

### ISSUE THREAD

**Issue by kStor2poche** [ForgottenMaster/forgottenmaster.github.io#1]
Hi, first of all, thank you very much for the content !

Just a small bug, it looks like since your last updates, all of the links now lead to localhost:1313/something instead of forgottenmaster.github.io/something.

**Comment by ForgottenMaster** [comment]
Hi there! Thank you for the issue. I've investigated and it seems the links I've tried all navigate to the correct domain. I did however move all my notes to an Obsidian vault as I find the experience of navigating an Obsidian vault to find the information required nicer than on a static website. The vault can be found here: https://github.com/ForgottenMaster/obsidian-vault

Is it possible you're using old links to pages that no longer exist (due to the change over to using an Obsidian vault for knowledge storage)?

**Comment by kStor2poche** [comment]
Ok, thanks ! It seems your notes are still hosted on your github.io if you still have a link to them smh (reloading with cache clear still loads the page), thanks for pointing me out to your obsidian vault anyways, will be using that instead then !
